apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: zech-sh-ingress
  labels:
    app: zech-sh
  annotations:
    kubernetes.io/ingress.class: traefik
    cert-manager.io/cluster-issuer: letsencrypt-production
spec:
  tls:
    - hosts:
        - zech.sh
        - dump.zech.sh
        - scan.zech.sh
      secretName: zech-sh-tls
  rules:
    - host: zech.sh
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: zech-sh
                port:
                  number: 8080
    - host: dump.zech.sh
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: zech-sh
                port:
                  number: 8080
    - host: scan.zech.sh
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: zech-sh
                port:
                  number: 8080
