apiVersion: v1
kind: Service
metadata:
  name: zech-sh
  labels:
    app: zech-sh
spec:
  type: ClusterIP
  selector:
    app: zech-sh
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
